# docker build -t openrunlog/mongodb-server

FROM ubuntu:12.04

RUN apt-get update
RUN apt-get install -y curl

# mongodb
RUN curl -O http://downloads.mongodb.org/linux/mongodb-linux-x86_64-2.4.8.tgz
RUN tar -zxvf mongodb-linux-x86_64-2.4.8.tgz
RUN mkdir -p /data/db

EXPOSE 27017
ENTRYPOINT ["mongodb-linux-x86_64-2.4.8/bin/mongod", "--smallfiles"]
