# docker build -t openrunlog/redis-server

## REDIS

FROM ubuntu:12.04

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y build-essential

# redis
RUN curl -O http://download.redis.io/redis-stable.tar.gz
RUN tar xvzf redis-stable.tar.gz
WORKDIR redis-stable
RUN make

EXPOSE 6379
RUN echo bind 0.0.0.0 > src/redis.conf
ENTRYPOINT ["src/redis-server", "src/redis.conf"]
